# Git branch in prompt.
# source /Library/Developer/CommandLineTools/usr/share/git-core/git-prompt.sh
source ~/.git-prompt.sh
alias dir='ls -alhF --color'
eval "$(pyenv init -)"

export GIT_PS1_SHOWDIRTYSTATE=1
export PS1='\[\033[01;34m\]🐸  \w\[\033[01;33m\]$(__git_ps1)\[\033[01;34m\] \$\[\033[00m\] '

# Set CLICOLOR if you want Ansi Colors in iTerm2
export CLICOLOR=1
# Set colors to match iTerm2 Terminal Colors
export TERM=xterm-256color

# Aliases
alias subl="open ~/../../Applications/Sublime\ Text.app/"
export PATH=/usr/local/bin:$PATH
source /usr/local/opt/chruby/share/chruby/chruby.sh
source /usr/local/opt/chruby/share/chruby/auto.sh
export PGDATA=/usr/local/var/postgres
export PGHOST=/tmp

# git commamands simplified
alias gst='git status'
alias gco='git checkout'
alias gci='git commit'
alias grb='git rebase'
alias gbr='git branch'
alias gad='git add -A'
alias gpl='git pull'
alias gpu='git push'
alias glg='git log --date-order --all --graph --format="%C(green)%h%Creset %C(yellow)%an%Creset %C(blue bold)%ar%Creset %C(red bold)%d%Creset%s"'
alias glg2='git log --date-order --all --graph --name-status --format="%C(green)%H%Creset %C(yellow)%an%Creset %C(blue bold)%ar%Creset %C(red bold)%d%Creset%s"'

# ls alias for color-mode
alias lh='ls -lhaG'

# up 'n' folders
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

# grep with color
alias grep='grep --color=auto'

# processes
#alias ps='ps -ax'

# refresh shell
alias reload='source ~/.bash_profile'

alias be='bundle exec'
alias rpry='bundle exec pry -r ./config/environment'

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
